// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

abstract class Native {
  Future<String> getVersion({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetVersionConstMeta;

  Future<String> pingDevice({required String deviceId, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPingDeviceConstMeta;

  Future<List<Device>> discoverDevices({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDiscoverDevicesConstMeta;

  Future<String> receiveFile({required String savePath, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReceiveFileConstMeta;

  Future<String> sendFile(
      {required String filePath, required String targetIp, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSendFileConstMeta;

  Future<String> sendMessage(
      {required String message, required String targetIp, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSendMessageConstMeta;

  Future<String> receiveMessage({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kReceiveMessageConstMeta;
}

class Device {
  final String id;
  final String name;
  final String ip;
  final int port;

  const Device({
    required this.id,
    required this.name,
    required this.ip,
    required this.port,
  });
}

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<String> getVersion({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_version(port_),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kGetVersionConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetVersionConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_version",
        argNames: [],
      );

  Future<String> pingDevice({required String deviceId, dynamic hint}) {
    var arg0 = _platform.api2wire_String(deviceId);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ping_device(port_, arg0),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kPingDeviceConstMeta,
      argValues: [deviceId],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kPingDeviceConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ping_device",
        argNames: ["deviceId"],
      );

  Future<List<Device>> discoverDevices({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_discover_devices(port_),
      parseSuccessData: _wire2api_list_device,
      parseErrorData: null,
      constMeta: kDiscoverDevicesConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kDiscoverDevicesConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "discover_devices",
        argNames: [],
      );

  Future<String> receiveFile({required String savePath, dynamic hint}) {
    var arg0 = _platform.api2wire_String(savePath);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_receive_file(port_, arg0),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kReceiveFileConstMeta,
      argValues: [savePath],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kReceiveFileConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "receive_file",
        argNames: ["savePath"],
      );

  Future<String> sendFile(
      {required String filePath, required String targetIp, dynamic hint}) {
    var arg0 = _platform.api2wire_String(filePath);
    var arg1 = _platform.api2wire_String(targetIp);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_send_file(port_, arg0, arg1),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kSendFileConstMeta,
      argValues: [filePath, targetIp],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSendFileConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "send_file",
        argNames: ["filePath", "targetIp"],
      );

  Future<String> sendMessage(
      {required String message, required String targetIp, dynamic hint}) {
    var arg0 = _platform.api2wire_String(message);
    var arg1 = _platform.api2wire_String(targetIp);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_send_message(port_, arg0, arg1),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kSendMessageConstMeta,
      argValues: [message, targetIp],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSendMessageConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "send_message",
        argNames: ["message", "targetIp"],
      );

  Future<String> receiveMessage({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_receive_message(port_),
      parseSuccessData: _wire2api_String,
      parseErrorData: null,
      constMeta: kReceiveMessageConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kReceiveMessageConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "receive_message",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  Device _wire2api_device(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Device(
      id: _wire2api_String(arr[0]),
      name: _wire2api_String(arr[1]),
      ip: _wire2api_String(arr[2]),
      port: _wire2api_u16(arr[3]),
    );
  }

  List<Device> _wire2api_list_device(dynamic raw) {
    return (raw as List<dynamic>).map(_wire2api_device).toList();
  }

  int _wire2api_u16(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class NativePlatform extends FlutterRustBridgeBase<NativeWire> {
  NativePlatform(ffi.DynamicLibrary dylib) : super(NativeWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class NativeWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_get_version(
    int port_,
  ) {
    return _wire_get_version(
      port_,
    );
  }

  late final _wire_get_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_version');
  late final _wire_get_version =
      _wire_get_versionPtr.asFunction<void Function(int)>();

  void wire_ping_device(
    int port_,
    ffi.Pointer<wire_uint_8_list> device_id,
  ) {
    return _wire_ping_device(
      port_,
      device_id,
    );
  }

  late final _wire_ping_devicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_ping_device');
  late final _wire_ping_device = _wire_ping_devicePtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_discover_devices(
    int port_,
  ) {
    return _wire_discover_devices(
      port_,
    );
  }

  late final _wire_discover_devicesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_discover_devices');
  late final _wire_discover_devices =
      _wire_discover_devicesPtr.asFunction<void Function(int)>();

  void wire_receive_file(
    int port_,
    ffi.Pointer<wire_uint_8_list> save_path,
  ) {
    return _wire_receive_file(
      port_,
      save_path,
    );
  }

  late final _wire_receive_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_receive_file');
  late final _wire_receive_file = _wire_receive_filePtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_send_file(
    int port_,
    ffi.Pointer<wire_uint_8_list> file_path,
    ffi.Pointer<wire_uint_8_list> target_ip,
  ) {
    return _wire_send_file(
      port_,
      file_path,
      target_ip,
    );
  }

  late final _wire_send_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_send_file');
  late final _wire_send_file = _wire_send_filePtr.asFunction<
      void Function(
          int, ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_send_message(
    int port_,
    ffi.Pointer<wire_uint_8_list> message,
    ffi.Pointer<wire_uint_8_list> target_ip,
  ) {
    return _wire_send_message(
      port_,
      message,
      target_ip,
    );
  }

  late final _wire_send_messagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_send_message');
  late final _wire_send_message = _wire_send_messagePtr.asFunction<
      void Function(
          int, ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_receive_message(
    int port_,
  ) {
    return _wire_receive_message(
      port_,
    );
  }

  late final _wire_receive_messagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_receive_message');
  late final _wire_receive_message =
      _wire_receive_messagePtr.asFunction<void Function(int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_uint_8_list> Function(ffi.Int32)>>(
      'new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
